spring.application.name=book_assistant
server.port=8042

#spring.datasource.url=jdbc:postgresql://localhost:5432/books
#spring.datasource.username=postgres
#spring.datasource.password=Pp393410
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/books-reservation-bd
spring.datasource.username=postgres
spring.datasource.password=Pp393410
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true